### ISSUE TITLE
Komihash 5

### ISSUE THREAD

**Issue by avaneev** [thynson/rust-komihash#1]
Hi! If you have not noticed, komihash5 is available.
https://github.com/avaneev/komihash
Thanks for the port.

**Comment by thynson** [comment]
Thanks for reminding.

**Comment by jianshu93** [comment]
5.24? see here: https://github.com/dynatrace-oss/hash4j/issues/352,

Best,
Jianshu

**Comment by avaneev** [comment]
The latest is v5.27 - the branching was considerably reduced since v5.10.
